# Generated by Django 5.1.5 on 2025-01-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creator_name', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('images', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
